# Generated by Django 4.2.7 on 2025-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='package',
            field=models.CharField(choices=[('basic', 'Базовая версия'), ('custom', 'Кастомная версия')], default='basic', max_length=20),
        ),
    ]
