# Generated by Django 4.2.7 on 2025-11-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_contactform_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Фавикон (иконка сайта)')),
                ('gallery_title', models.CharField(default='Галерея скриншотов', max_length=200, verbose_name="Заголовок секции 'Галерея'")),
                ('gallery_subtitle', models.TextField(default='Посмотрите на реалистичную графику и разнообразие локаций', verbose_name="Подзаголовок секции 'Галерея'")),
                ('app_gallery_title', models.CharField(default='Интерфейс приложения', max_length=200, verbose_name="Заголовок секции 'Интерфейс'")),
                ('app_gallery_subtitle', models.TextField(default='Удобный и интуитивный интерфейс для комфортной работы', verbose_name="Подзаголовок секции 'Интерфейс'")),
                ('versions_title', models.CharField(default='Версии симулятора', max_length=200, verbose_name="Заголовок секции 'Версии'")),
                ('versions_subtitle', models.TextField(default='Выберите версию, которая подходит именно вам', verbose_name="Подзаголовок секции 'Версии'")),
                ('purchase_options_title', models.CharField(default='Варианты приобретения', max_length=200, verbose_name="Заголовок секции 'Варианты приобретения'")),
                ('purchase_options_subtitle', models.TextField(default='Выберите подходящий тариф для ваших потребностей', verbose_name="Подзаголовок секции 'Варианты приобретения'")),
            ],
            options={
                'verbose_name': '0. Общие настройки страницы',
                'verbose_name_plural': '0. Общие настройки страницы',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOptionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_name', models.CharField(default='Базовая версия', max_length=100, verbose_name='Название тарифа (Базовый)')),
                ('basic_price', models.CharField(default='5000 руб', max_length=100, verbose_name='Цена (Базовый)')),
                ('basic_features', models.TextField(default='Полный доступ к симулятору\nВсе локации и режимы\nТехническая поддержка', verbose_name='Особенности (Базовый)')),
                ('custom_name', models.CharField(default='Кастомная версия', max_length=100, verbose_name='Название тарифа (Кастомный)')),
                ('custom_price', models.CharField(default='Цена по запросу', max_length=100, verbose_name='Цена (Кастомный)')),
                ('custom_features', models.TextField(default='Индивидуальная разработка\nПерсональные настройки\nПриоритетная поддержка', verbose_name='Особенности (Кастомный)')),
            ],
            options={
                'verbose_name': "8. Секция 'Варианты приобретения'",
                'verbose_name_plural': "8. Секция 'Варианты приобретения'",
            },
        ),
        migrations.CreateModel(
            name='VersionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_title', models.CharField(default='Базовая версия', max_length=100, verbose_name='Название (Базовая)')),
                ('basic_description', models.TextField(default='Для школ, вузов, СПО, дополнительного образования. Подходит для обучения навыкам полета на квадрокоптерах весом до 30 кг и подготовки к решению определенных видов задач.', verbose_name='Описание (Базовая)')),
                ('basic_supported_os', models.CharField(default='Linux, Windows, macOS, РЕД ОС, Astra Linux, uncomOS', max_length=300, verbose_name='Поддерживаемые ОС (Базовая)')),
                ('custom_title', models.CharField(default='Кастомная версия', max_length=100, verbose_name='Название (Кастомная)')),
                ('custom_description', models.TextField(default='Разработка версии под ваши уникальные требования.', verbose_name='Описание (Кастомная)')),
                ('custom_supported_os', models.CharField(default='Linux, Windows, macOS, РЕД ОС, Astra Linux, uncomOS', max_length=300, verbose_name='Поддерживаемые ОС (Кастомная)')),
            ],
            options={
                'verbose_name': "6. Секция 'Версии симулятора'",
                'verbose_name_plural': "6. Секция 'Версии симулятора'",
            },
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='PurchaseOption',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.AlterModelOptions(
            name='aboutblock',
            options={'verbose_name': '1. Главный блок', 'verbose_name_plural': '1. Главный блок'},
        ),
        migrations.AlterModelOptions(
            name='appscreenshot',
            options={'ordering': ['order'], 'verbose_name': 'Скриншот интерфейса', 'verbose_name_plural': '5. Скриншоты интерфейса'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': '9. Контакты и футер', 'verbose_name_plural': '9. Контакты и футер'},
        ),
        migrations.AlterModelOptions(
            name='fpvmode',
            options={'verbose_name': "7. Блок 'FPV режим'", 'verbose_name_plural': "7. Блок 'FPV режим'"},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': "3. Блок 'О продукте'", 'verbose_name_plural': "3. Блок 'О продукте'"},
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'verbose_name': 'Скриншот локации', 'verbose_name_plural': 'Скриншоты локаций'},
        ),
        migrations.AlterModelOptions(
            name='screenshotalbum',
            options={'ordering': ['order'], 'verbose_name': 'Альбом скриншотов локаций', 'verbose_name_plural': '4. Альбомы скриншотов локаций'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'verbose_name': "2. Секция 'Трейлер'", 'verbose_name_plural': "2. Секция 'Трейлер'"},
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Изображение фона Hero (верхняя секция)'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_subtitle',
            field=models.TextField(default='Мы всегда готовы ответить на ваши вопросы и обсудить сотрудничество.', verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_title',
            field=models.CharField(default='Свяжитесь с нами', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='fpvmode',
            name='title',
            field=models.CharField(default='FPV режим', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='title',
            field=models.CharField(default='О продукте', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='subtitle',
            field=models.TextField(default='Посмотрите видео, чтобы узнать больше о возможностях нашего симулятора', verbose_name='Подзаголовок секции'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='title',
            field=models.CharField(default='Трейлер симулятора', max_length=200, verbose_name='Заголовок секции'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='subtitle',
            field=models.CharField(default='Симулятор FPV дронов с детально проработанной физикой', max_length=200, verbose_name='Подзаголовок (не используется)'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='text_in_frame',
            field=models.TextField(default='Отрабатывайте пилотирование в реальных полетных условиях и на разнообразных картах в режиме свободного полета. Усложните задачу: выследите и найдите подвижную цель на локациях с помощью специального режима «Поиск».', verbose_name='Текст в рамке'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title',
            field=models.CharField(default='Тренажер БПЛА с реалистичной физикой и режимом от первого лица', max_length=200, verbose_name='Заголовок на главном экране'),
        ),
        migrations.AlterField(
            model_name='appscreenshot',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (не используется)'),
        ),
        migrations.AlterField(
            model_name='appscreenshot',
            name='image',
            field=models.ImageField(upload_to='app_screenshots/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='appscreenshot',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='appscreenshot',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название скриншота'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(default='m.korovob@yandex.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='our_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Наш логотип (в футере)'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='partner_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип партнера (в футере)'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.CharField(default='8 900 478 43 84', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='fpvmode',
            name='description',
            field=models.TextField(default='Симулятор FPV дронов с детально проработанной физикой для тренировок в режиме от первого лица.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fpvmode',
            name='image',
            field=models.ImageField(upload_to='fpv_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='description',
            field=models.TextField(default='...', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='landing.screenshotalbum', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='caption',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='screenshots/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='screenshotalbum',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='screenshotalbum',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название локации'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='local_video',
            field=models.FileField(blank=True, help_text='Либо загрузите видеофайл', null=True, upload_to='videos/', verbose_name='Локальное видео'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео с YouTube или другого видеохостинга', null=True, verbose_name='Ссылка на YouTube видео'),
        ),
    ]
